// main.cpp
#include "main.h"
#include "FastGpio.hpp"

int main(void) {
  HAL_Init();
  SystemClock_Config();     // Generated by CubeMX
  // MX_GPIO_Init();        // You can skip this if using only FastGpio

  // Example: Onboard LED on many Nucleo boards is PA5
  FastGpio led(GPIOA, 5);

  // Example: User button on many Nucleo boards is PC13 (active low)
  FastGpio button(GPIOC, 13);  // Configured as output by default → fix for input

  // Better: Create a separate input version or modify constructor
  // Quick fix: Manually configure button as input with pull-up
  __HAL_RCC_GPIOC_CLK_ENABLE();
  GPIOC->MODER &= ~(3u << (13 * 2));     // Input mode
  GPIOC->PUPDR &= ~(3u << (13 * 2));
  GPIOC->PUPDR |=  (1u << (13 * 2));     // Pull-up

  uint32_t delay = 500;  // Default blink delay in ms

  while (1) {
    led.toggle();

    // If user button is pressed (low), blink faster
    if (button.read() == 0) {  // Active low
      delay = 100;
    } else {
      delay = 500;
    }

    HAL_Delay(delay);
  }
}